# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         YAML-AppConfig
version:      0.16
version_from: lib/YAML/AppConfig.pm
installdirs:  site
requires:
    Carp:                          0
    Storable:                      0
    UNIVERSAL:                     0
    YAML:                          0.38
    YAML::Syck:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
